const FIREBASE_API_KEY = "AIzaSyAjH5Y8h5o6OAxPwxqRfoBRCsIzV2ou3AA"
const FIREBASE_AUTH_DOMAIN = "vob-checker.firebaseapp.com"
const FIREBASE_PROJECT_ID = "vob-checker"
const FIREBASE_STORAGE_BUCKET = "vob-checker.appspot.com"
const FIREBASE_MESSAGING_SENDER_ID = "622487801663"
const FIREBASE_APP_ID = "1:622487801663:web:a60573646cbbb561a90d8a"
const FIREBASE_MEASUREMENT_ID = "G-Q6J3KYG3CE"

module.exports = {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID
}